apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamiq
  namespace: gamesocial
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gamiq
  template:
    metadata:
      labels:
        app: gamiq
    spec:
      # Uncomment imagePullSecrets if your repo is PRIVATE
      # imagePullSecrets:
      #   - name: ghcr-secret
      containers:
        - name: gamiq
          image: ghcr.io/vishal-shaw20/gamesocial-gamiq:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: gamiq-secrets
          env:
            - name: REDIS_URL
              value: "redis://redis.gamesocial.svc.cluster.local:6379/0"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: gamiq-artifacts
              mountPath: /app/recommender/artifacts
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "7Gi"
              cpu: "2"
      volumes:
        - name: gamiq-artifacts
          persistentVolumeClaim:
            claimName: gamiq-artifacts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gamiq
  namespace: gamesocial
spec:
  selector:
    app: gamiq
  ports:
    - port: 8000
      targetPort: 8000
